namespace StoreManagerPro
{
    partial class AdminMainPage
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(AdminMainPage));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges8 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges9 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.controlboxTurnOff = new Guna.UI2.WinForms.Guna2ControlBox();
            this.controlboxMinimize = new Guna.UI2.WinForms.Guna2ControlBox();
            this.guna2Panel1 = new Guna.UI2.WinForms.Guna2Panel();
            this.btnSubcategory = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnProvider = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuPictureBox1 = new Bunifu.UI.WinForms.BunifuPictureBox();
            this.btnSize = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnColor = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnOrder = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnHome = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnCustomer = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnCategory = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnProduct = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.flowLayoutPanel = new System.Windows.Forms.FlowLayoutPanel();
            this.guna2Panel1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuPictureBox1)).BeginInit();
            this.SuspendLayout();
            // 
            // controlboxTurnOff
            // 
            this.controlboxTurnOff.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.controlboxTurnOff.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(42)))), ((int)(((byte)(133)))));
            this.controlboxTurnOff.HoverState.FillColor = System.Drawing.Color.Red;
            this.controlboxTurnOff.HoverState.Parent = this.controlboxTurnOff;
            this.controlboxTurnOff.IconColor = System.Drawing.Color.White;
            this.controlboxTurnOff.Location = new System.Drawing.Point(1399, 3);
            this.controlboxTurnOff.Name = "controlboxTurnOff";
            this.controlboxTurnOff.ShadowDecoration.Parent = this.controlboxTurnOff;
            this.controlboxTurnOff.Size = new System.Drawing.Size(32, 27);
            this.controlboxTurnOff.TabIndex = 12;
            // 
            // controlboxMinimize
            // 
            this.controlboxMinimize.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.controlboxMinimize.ControlBoxType = Guna.UI2.WinForms.Enums.ControlBoxType.MinimizeBox;
            this.controlboxMinimize.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(42)))), ((int)(((byte)(133)))));
            this.controlboxMinimize.HoverState.Parent = this.controlboxMinimize;
            this.controlboxMinimize.IconColor = System.Drawing.Color.White;
            this.controlboxMinimize.Location = new System.Drawing.Point(1361, 3);
            this.controlboxMinimize.Name = "controlboxMinimize";
            this.controlboxMinimize.ShadowDecoration.Parent = this.controlboxMinimize;
            this.controlboxMinimize.Size = new System.Drawing.Size(32, 27);
            this.controlboxMinimize.TabIndex = 13;
            // 
            // guna2Panel1
            // 
            this.guna2Panel1.BackColor = System.Drawing.Color.Transparent;
            this.guna2Panel1.BorderColor = System.Drawing.Color.Transparent;
            this.guna2Panel1.BorderRadius = 20;
            this.guna2Panel1.Controls.Add(this.btnSubcategory);
            this.guna2Panel1.Controls.Add(this.btnProvider);
            this.guna2Panel1.Controls.Add(this.bunifuPictureBox1);
            this.guna2Panel1.Controls.Add(this.btnSize);
            this.guna2Panel1.Controls.Add(this.btnColor);
            this.guna2Panel1.Controls.Add(this.btnOrder);
            this.guna2Panel1.Controls.Add(this.btnHome);
            this.guna2Panel1.Controls.Add(this.btnCustomer);
            this.guna2Panel1.Controls.Add(this.btnCategory);
            this.guna2Panel1.Controls.Add(this.btnProduct);
            this.guna2Panel1.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(252)))), ((int)(((byte)(175)))), ((int)(((byte)(23)))));
            this.guna2Panel1.Location = new System.Drawing.Point(-28, 53);
            this.guna2Panel1.Name = "guna2Panel1";
            this.guna2Panel1.ShadowDecoration.Parent = this.guna2Panel1;
            this.guna2Panel1.Size = new System.Drawing.Size(282, 891);
            this.guna2Panel1.TabIndex = 8;
            // 
            // btnSubcategory
            // 
            this.btnSubcategory.AllowAnimations = true;
            this.btnSubcategory.AllowMouseEffects = true;
            this.btnSubcategory.AllowToggling = true;
            this.btnSubcategory.AnimationSpeed = 200;
            this.btnSubcategory.AutoGenerateColors = false;
            this.btnSubcategory.AutoRoundBorders = false;
            this.btnSubcategory.AutoSizeLeftIcon = true;
            this.btnSubcategory.AutoSizeRightIcon = true;
            this.btnSubcategory.BackColor = System.Drawing.Color.Transparent;
            this.btnSubcategory.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(252)))), ((int)(((byte)(175)))), ((int)(((byte)(23)))));
            this.btnSubcategory.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnSubcategory.BackgroundImage")));
            this.btnSubcategory.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSubcategory.ButtonText = "Subcategory";
            this.btnSubcategory.ButtonTextMarginLeft = 0;
            this.btnSubcategory.ColorContrastOnClick = 45;
            this.btnSubcategory.ColorContrastOnHover = 45;
            this.btnSubcategory.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btnSubcategory.CustomizableEdges = borderEdges1;
            this.btnSubcategory.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnSubcategory.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnSubcategory.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnSubcategory.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnSubcategory.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnSubcategory.Font = new System.Drawing.Font("Segoe UI Semibold", 11F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnSubcategory.ForeColor = System.Drawing.Color.White;
            this.btnSubcategory.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnSubcategory.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btnSubcategory.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnSubcategory.IconMarginLeft = 11;
            this.btnSubcategory.IconPadding = 10;
            this.btnSubcategory.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnSubcategory.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btnSubcategory.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnSubcategory.IconSize = 25;
            this.btnSubcategory.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(252)))), ((int)(((byte)(175)))), ((int)(((byte)(23)))));
            this.btnSubcategory.IdleBorderRadius = 35;
            this.btnSubcategory.IdleBorderThickness = 1;
            this.btnSubcategory.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(252)))), ((int)(((byte)(175)))), ((int)(((byte)(23)))));
            this.btnSubcategory.IdleIconLeftImage = null;
            this.btnSubcategory.IdleIconRightImage = null;
            this.btnSubcategory.IndicateFocus = true;
            this.btnSubcategory.Location = new System.Drawing.Point(55, 460);
            this.btnSubcategory.Name = "btnSubcategory";
            this.btnSubcategory.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnSubcategory.OnDisabledState.BorderRadius = 35;
            this.btnSubcategory.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSubcategory.OnDisabledState.BorderThickness = 1;
            this.btnSubcategory.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnSubcategory.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnSubcategory.OnDisabledState.IconLeftImage = null;
            this.btnSubcategory.OnDisabledState.IconRightImage = null;
            this.btnSubcategory.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(42)))), ((int)(((byte)(133)))));
            this.btnSubcategory.onHoverState.BorderRadius = 35;
            this.btnSubcategory.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSubcategory.onHoverState.BorderThickness = 1;
            this.btnSubcategory.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(42)))), ((int)(((byte)(133)))));
            this.btnSubcategory.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnSubcategory.onHoverState.IconLeftImage = null;
            this.btnSubcategory.onHoverState.IconRightImage = null;
            this.btnSubcategory.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(252)))), ((int)(((byte)(175)))), ((int)(((byte)(23)))));
            this.btnSubcategory.OnIdleState.BorderRadius = 35;
            this.btnSubcategory.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSubcategory.OnIdleState.BorderThickness = 1;
            this.btnSubcategory.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(252)))), ((int)(((byte)(175)))), ((int)(((byte)(23)))));
            this.btnSubcategory.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnSubcategory.OnIdleState.IconLeftImage = null;
            this.btnSubcategory.OnIdleState.IconRightImage = null;
            this.btnSubcategory.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(42)))), ((int)(((byte)(133)))));
            this.btnSubcategory.OnPressedState.BorderRadius = 35;
            this.btnSubcategory.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSubcategory.OnPressedState.BorderThickness = 1;
            this.btnSubcategory.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnSubcategory.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnSubcategory.OnPressedState.IconLeftImage = null;
            this.btnSubcategory.OnPressedState.IconRightImage = null;
            this.btnSubcategory.Size = new System.Drawing.Size(173, 41);
            this.btnSubcategory.TabIndex = 12;
            this.btnSubcategory.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnSubcategory.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnSubcategory.TextMarginLeft = 0;
            this.btnSubcategory.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnSubcategory.UseDefaultRadiusAndThickness = true;
            this.btnSubcategory.Click += new System.EventHandler(this.btnSubcategory_Click);
            // 
            // btnProvider
            // 
            this.btnProvider.AllowAnimations = true;
            this.btnProvider.AllowMouseEffects = true;
            this.btnProvider.AllowToggling = true;
            this.btnProvider.AnimationSpeed = 200;
            this.btnProvider.AutoGenerateColors = false;
            this.btnProvider.AutoRoundBorders = false;
            this.btnProvider.AutoSizeLeftIcon = true;
            this.btnProvider.AutoSizeRightIcon = true;
            this.btnProvider.BackColor = System.Drawing.Color.Transparent;
            this.btnProvider.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(252)))), ((int)(((byte)(175)))), ((int)(((byte)(23)))));
            this.btnProvider.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnProvider.BackgroundImage")));
            this.btnProvider.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnProvider.ButtonText = "Provider";
            this.btnProvider.ButtonTextMarginLeft = 0;
            this.btnProvider.ColorContrastOnClick = 45;
            this.btnProvider.ColorContrastOnHover = 45;
            this.btnProvider.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btnProvider.CustomizableEdges = borderEdges2;
            this.btnProvider.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnProvider.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnProvider.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnProvider.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnProvider.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnProvider.Font = new System.Drawing.Font("Segoe UI Semibold", 11F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnProvider.ForeColor = System.Drawing.Color.White;
            this.btnProvider.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnProvider.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btnProvider.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnProvider.IconMarginLeft = 11;
            this.btnProvider.IconPadding = 10;
            this.btnProvider.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnProvider.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btnProvider.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnProvider.IconSize = 25;
            this.btnProvider.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(252)))), ((int)(((byte)(175)))), ((int)(((byte)(23)))));
            this.btnProvider.IdleBorderRadius = 35;
            this.btnProvider.IdleBorderThickness = 1;
            this.btnProvider.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(252)))), ((int)(((byte)(175)))), ((int)(((byte)(23)))));
            this.btnProvider.IdleIconLeftImage = null;
            this.btnProvider.IdleIconRightImage = null;
            this.btnProvider.IndicateFocus = true;
            this.btnProvider.Location = new System.Drawing.Point(55, 685);
            this.btnProvider.Name = "btnProvider";
            this.btnProvider.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnProvider.OnDisabledState.BorderRadius = 35;
            this.btnProvider.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnProvider.OnDisabledState.BorderThickness = 1;
            this.btnProvider.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnProvider.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnProvider.OnDisabledState.IconLeftImage = null;
            this.btnProvider.OnDisabledState.IconRightImage = null;
            this.btnProvider.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(42)))), ((int)(((byte)(133)))));
            this.btnProvider.onHoverState.BorderRadius = 35;
            this.btnProvider.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnProvider.onHoverState.BorderThickness = 1;
            this.btnProvider.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(42)))), ((int)(((byte)(133)))));
            this.btnProvider.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnProvider.onHoverState.IconLeftImage = null;
            this.btnProvider.onHoverState.IconRightImage = null;
            this.btnProvider.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(252)))), ((int)(((byte)(175)))), ((int)(((byte)(23)))));
            this.btnProvider.OnIdleState.BorderRadius = 35;
            this.btnProvider.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnProvider.OnIdleState.BorderThickness = 1;
            this.btnProvider.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(252)))), ((int)(((byte)(175)))), ((int)(((byte)(23)))));
            this.btnProvider.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnProvider.OnIdleState.IconLeftImage = null;
            this.btnProvider.OnIdleState.IconRightImage = null;
            this.btnProvider.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(42)))), ((int)(((byte)(133)))));
            this.btnProvider.OnPressedState.BorderRadius = 35;
            this.btnProvider.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnProvider.OnPressedState.BorderThickness = 1;
            this.btnProvider.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnProvider.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnProvider.OnPressedState.IconLeftImage = null;
            this.btnProvider.OnPressedState.IconRightImage = null;
            this.btnProvider.Size = new System.Drawing.Size(173, 41);
            this.btnProvider.TabIndex = 11;
            this.btnProvider.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnProvider.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnProvider.TextMarginLeft = 0;
            this.btnProvider.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnProvider.UseDefaultRadiusAndThickness = true;
            this.btnProvider.Click += new System.EventHandler(this.btnProvider_Click);
            // 
            // bunifuPictureBox1
            // 
            this.bunifuPictureBox1.AllowFocused = false;
            this.bunifuPictureBox1.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.bunifuPictureBox1.AutoSizeHeight = true;
            this.bunifuPictureBox1.BorderRadius = 65;
            this.bunifuPictureBox1.Image = ((System.Drawing.Image)(resources.GetObject("bunifuPictureBox1.Image")));
            this.bunifuPictureBox1.IsCircle = true;
            this.bunifuPictureBox1.Location = new System.Drawing.Point(83, 15);
            this.bunifuPictureBox1.Name = "bunifuPictureBox1";
            this.bunifuPictureBox1.Size = new System.Drawing.Size(130, 130);
            this.bunifuPictureBox1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.bunifuPictureBox1.TabIndex = 10;
            this.bunifuPictureBox1.TabStop = false;
            this.bunifuPictureBox1.Type = Bunifu.UI.WinForms.BunifuPictureBox.Types.Circle;
            // 
            // btnSize
            // 
            this.btnSize.AllowAnimations = true;
            this.btnSize.AllowMouseEffects = true;
            this.btnSize.AllowToggling = true;
            this.btnSize.AnimationSpeed = 200;
            this.btnSize.AutoGenerateColors = false;
            this.btnSize.AutoRoundBorders = false;
            this.btnSize.AutoSizeLeftIcon = true;
            this.btnSize.AutoSizeRightIcon = true;
            this.btnSize.BackColor = System.Drawing.Color.Transparent;
            this.btnSize.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(252)))), ((int)(((byte)(175)))), ((int)(((byte)(23)))));
            this.btnSize.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnSize.BackgroundImage")));
            this.btnSize.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSize.ButtonText = "Size";
            this.btnSize.ButtonTextMarginLeft = 0;
            this.btnSize.ColorContrastOnClick = 45;
            this.btnSize.ColorContrastOnHover = 45;
            this.btnSize.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.btnSize.CustomizableEdges = borderEdges3;
            this.btnSize.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnSize.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnSize.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnSize.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnSize.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnSize.Font = new System.Drawing.Font("Segoe UI Semibold", 11F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnSize.ForeColor = System.Drawing.Color.White;
            this.btnSize.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnSize.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btnSize.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnSize.IconMarginLeft = 11;
            this.btnSize.IconPadding = 10;
            this.btnSize.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnSize.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btnSize.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnSize.IconSize = 25;
            this.btnSize.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(252)))), ((int)(((byte)(175)))), ((int)(((byte)(23)))));
            this.btnSize.IdleBorderRadius = 35;
            this.btnSize.IdleBorderThickness = 1;
            this.btnSize.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(252)))), ((int)(((byte)(175)))), ((int)(((byte)(23)))));
            this.btnSize.IdleIconLeftImage = null;
            this.btnSize.IdleIconRightImage = null;
            this.btnSize.IndicateFocus = true;
            this.btnSize.Location = new System.Drawing.Point(55, 610);
            this.btnSize.Name = "btnSize";
            this.btnSize.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnSize.OnDisabledState.BorderRadius = 35;
            this.btnSize.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSize.OnDisabledState.BorderThickness = 1;
            this.btnSize.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnSize.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnSize.OnDisabledState.IconLeftImage = null;
            this.btnSize.OnDisabledState.IconRightImage = null;
            this.btnSize.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(42)))), ((int)(((byte)(133)))));
            this.btnSize.onHoverState.BorderRadius = 35;
            this.btnSize.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSize.onHoverState.BorderThickness = 1;
            this.btnSize.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(42)))), ((int)(((byte)(133)))));
            this.btnSize.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnSize.onHoverState.IconLeftImage = null;
            this.btnSize.onHoverState.IconRightImage = null;
            this.btnSize.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(252)))), ((int)(((byte)(175)))), ((int)(((byte)(23)))));
            this.btnSize.OnIdleState.BorderRadius = 35;
            this.btnSize.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSize.OnIdleState.BorderThickness = 1;
            this.btnSize.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(252)))), ((int)(((byte)(175)))), ((int)(((byte)(23)))));
            this.btnSize.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnSize.OnIdleState.IconLeftImage = null;
            this.btnSize.OnIdleState.IconRightImage = null;
            this.btnSize.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(42)))), ((int)(((byte)(133)))));
            this.btnSize.OnPressedState.BorderRadius = 35;
            this.btnSize.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSize.OnPressedState.BorderThickness = 1;
            this.btnSize.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnSize.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnSize.OnPressedState.IconLeftImage = null;
            this.btnSize.OnPressedState.IconRightImage = null;
            this.btnSize.Size = new System.Drawing.Size(173, 41);
            this.btnSize.TabIndex = 9;
            this.btnSize.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnSize.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnSize.TextMarginLeft = 0;
            this.btnSize.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnSize.UseDefaultRadiusAndThickness = true;
            this.btnSize.Click += new System.EventHandler(this.btnSize_Click);
            // 
            // btnColor
            // 
            this.btnColor.AllowAnimations = true;
            this.btnColor.AllowMouseEffects = true;
            this.btnColor.AllowToggling = true;
            this.btnColor.AnimationSpeed = 200;
            this.btnColor.AutoGenerateColors = false;
            this.btnColor.AutoRoundBorders = false;
            this.btnColor.AutoSizeLeftIcon = true;
            this.btnColor.AutoSizeRightIcon = true;
            this.btnColor.BackColor = System.Drawing.Color.Transparent;
            this.btnColor.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(252)))), ((int)(((byte)(175)))), ((int)(((byte)(23)))));
            this.btnColor.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnColor.BackgroundImage")));
            this.btnColor.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnColor.ButtonText = "Color";
            this.btnColor.ButtonTextMarginLeft = 0;
            this.btnColor.ColorContrastOnClick = 45;
            this.btnColor.ColorContrastOnHover = 45;
            this.btnColor.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.btnColor.CustomizableEdges = borderEdges4;
            this.btnColor.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnColor.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnColor.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnColor.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnColor.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnColor.Font = new System.Drawing.Font("Segoe UI Semibold", 11F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnColor.ForeColor = System.Drawing.Color.White;
            this.btnColor.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnColor.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btnColor.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnColor.IconMarginLeft = 11;
            this.btnColor.IconPadding = 10;
            this.btnColor.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnColor.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btnColor.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnColor.IconSize = 25;
            this.btnColor.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(252)))), ((int)(((byte)(175)))), ((int)(((byte)(23)))));
            this.btnColor.IdleBorderRadius = 35;
            this.btnColor.IdleBorderThickness = 1;
            this.btnColor.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(252)))), ((int)(((byte)(175)))), ((int)(((byte)(23)))));
            this.btnColor.IdleIconLeftImage = null;
            this.btnColor.IdleIconRightImage = null;
            this.btnColor.IndicateFocus = true;
            this.btnColor.Location = new System.Drawing.Point(55, 535);
            this.btnColor.Name = "btnColor";
            this.btnColor.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnColor.OnDisabledState.BorderRadius = 35;
            this.btnColor.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnColor.OnDisabledState.BorderThickness = 1;
            this.btnColor.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnColor.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnColor.OnDisabledState.IconLeftImage = null;
            this.btnColor.OnDisabledState.IconRightImage = null;
            this.btnColor.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(42)))), ((int)(((byte)(133)))));
            this.btnColor.onHoverState.BorderRadius = 35;
            this.btnColor.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnColor.onHoverState.BorderThickness = 1;
            this.btnColor.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(42)))), ((int)(((byte)(133)))));
            this.btnColor.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnColor.onHoverState.IconLeftImage = null;
            this.btnColor.onHoverState.IconRightImage = null;
            this.btnColor.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(252)))), ((int)(((byte)(175)))), ((int)(((byte)(23)))));
            this.btnColor.OnIdleState.BorderRadius = 35;
            this.btnColor.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnColor.OnIdleState.BorderThickness = 1;
            this.btnColor.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(252)))), ((int)(((byte)(175)))), ((int)(((byte)(23)))));
            this.btnColor.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnColor.OnIdleState.IconLeftImage = null;
            this.btnColor.OnIdleState.IconRightImage = null;
            this.btnColor.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(42)))), ((int)(((byte)(133)))));
            this.btnColor.OnPressedState.BorderRadius = 35;
            this.btnColor.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnColor.OnPressedState.BorderThickness = 1;
            this.btnColor.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnColor.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnColor.OnPressedState.IconLeftImage = null;
            this.btnColor.OnPressedState.IconRightImage = null;
            this.btnColor.Size = new System.Drawing.Size(173, 41);
            this.btnColor.TabIndex = 8;
            this.btnColor.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnColor.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnColor.TextMarginLeft = 0;
            this.btnColor.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnColor.UseDefaultRadiusAndThickness = true;
            this.btnColor.Click += new System.EventHandler(this.btnColor_Click);
            // 
            // btnOrder
            // 
            this.btnOrder.AllowAnimations = true;
            this.btnOrder.AllowMouseEffects = true;
            this.btnOrder.AllowToggling = true;
            this.btnOrder.AnimationSpeed = 200;
            this.btnOrder.AutoGenerateColors = false;
            this.btnOrder.AutoRoundBorders = false;
            this.btnOrder.AutoSizeLeftIcon = true;
            this.btnOrder.AutoSizeRightIcon = true;
            this.btnOrder.BackColor = System.Drawing.Color.Transparent;
            this.btnOrder.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(252)))), ((int)(((byte)(175)))), ((int)(((byte)(23)))));
            this.btnOrder.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnOrder.BackgroundImage")));
            this.btnOrder.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnOrder.ButtonText = "Order";
            this.btnOrder.ButtonTextMarginLeft = 0;
            this.btnOrder.ColorContrastOnClick = 45;
            this.btnOrder.ColorContrastOnHover = 45;
            this.btnOrder.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.btnOrder.CustomizableEdges = borderEdges5;
            this.btnOrder.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnOrder.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnOrder.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnOrder.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnOrder.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnOrder.Font = new System.Drawing.Font("Segoe UI Semibold", 11F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnOrder.ForeColor = System.Drawing.Color.White;
            this.btnOrder.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnOrder.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btnOrder.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnOrder.IconMarginLeft = 11;
            this.btnOrder.IconPadding = 10;
            this.btnOrder.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnOrder.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btnOrder.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnOrder.IconSize = 25;
            this.btnOrder.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(252)))), ((int)(((byte)(175)))), ((int)(((byte)(23)))));
            this.btnOrder.IdleBorderRadius = 35;
            this.btnOrder.IdleBorderThickness = 1;
            this.btnOrder.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(252)))), ((int)(((byte)(175)))), ((int)(((byte)(23)))));
            this.btnOrder.IdleIconLeftImage = null;
            this.btnOrder.IdleIconRightImage = null;
            this.btnOrder.IndicateFocus = true;
            this.btnOrder.Location = new System.Drawing.Point(40, 773);
            this.btnOrder.Name = "btnOrder";
            this.btnOrder.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnOrder.OnDisabledState.BorderRadius = 35;
            this.btnOrder.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnOrder.OnDisabledState.BorderThickness = 1;
            this.btnOrder.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnOrder.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnOrder.OnDisabledState.IconLeftImage = null;
            this.btnOrder.OnDisabledState.IconRightImage = null;
            this.btnOrder.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(42)))), ((int)(((byte)(133)))));
            this.btnOrder.onHoverState.BorderRadius = 35;
            this.btnOrder.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnOrder.onHoverState.BorderThickness = 1;
            this.btnOrder.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(42)))), ((int)(((byte)(133)))));
            this.btnOrder.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnOrder.onHoverState.IconLeftImage = null;
            this.btnOrder.onHoverState.IconRightImage = null;
            this.btnOrder.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(252)))), ((int)(((byte)(175)))), ((int)(((byte)(23)))));
            this.btnOrder.OnIdleState.BorderRadius = 35;
            this.btnOrder.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnOrder.OnIdleState.BorderThickness = 1;
            this.btnOrder.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(252)))), ((int)(((byte)(175)))), ((int)(((byte)(23)))));
            this.btnOrder.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnOrder.OnIdleState.IconLeftImage = null;
            this.btnOrder.OnIdleState.IconRightImage = null;
            this.btnOrder.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(42)))), ((int)(((byte)(133)))));
            this.btnOrder.OnPressedState.BorderRadius = 35;
            this.btnOrder.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnOrder.OnPressedState.BorderThickness = 1;
            this.btnOrder.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnOrder.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnOrder.OnPressedState.IconLeftImage = null;
            this.btnOrder.OnPressedState.IconRightImage = null;
            this.btnOrder.Size = new System.Drawing.Size(212, 41);
            this.btnOrder.TabIndex = 7;
            this.btnOrder.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnOrder.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnOrder.TextMarginLeft = 0;
            this.btnOrder.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnOrder.UseDefaultRadiusAndThickness = true;
            this.btnOrder.Click += new System.EventHandler(this.btnOrder_Click);
            // 
            // btnHome
            // 
            this.btnHome.AllowAnimations = true;
            this.btnHome.AllowMouseEffects = true;
            this.btnHome.AllowToggling = true;
            this.btnHome.AnimationSpeed = 200;
            this.btnHome.AutoGenerateColors = false;
            this.btnHome.AutoRoundBorders = false;
            this.btnHome.AutoSizeLeftIcon = true;
            this.btnHome.AutoSizeRightIcon = true;
            this.btnHome.BackColor = System.Drawing.Color.Transparent;
            this.btnHome.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(252)))), ((int)(((byte)(175)))), ((int)(((byte)(23)))));
            this.btnHome.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnHome.BackgroundImage")));
            this.btnHome.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnHome.ButtonText = "Home";
            this.btnHome.ButtonTextMarginLeft = 0;
            this.btnHome.ColorContrastOnClick = 45;
            this.btnHome.ColorContrastOnHover = 45;
            this.btnHome.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.btnHome.CustomizableEdges = borderEdges6;
            this.btnHome.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnHome.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnHome.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnHome.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnHome.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnHome.Font = new System.Drawing.Font("Segoe UI Semibold", 11F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnHome.ForeColor = System.Drawing.Color.White;
            this.btnHome.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnHome.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btnHome.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnHome.IconMarginLeft = 11;
            this.btnHome.IconPadding = 10;
            this.btnHome.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnHome.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btnHome.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnHome.IconSize = 25;
            this.btnHome.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(252)))), ((int)(((byte)(175)))), ((int)(((byte)(23)))));
            this.btnHome.IdleBorderRadius = 35;
            this.btnHome.IdleBorderThickness = 1;
            this.btnHome.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(252)))), ((int)(((byte)(175)))), ((int)(((byte)(23)))));
            this.btnHome.IdleIconLeftImage = null;
            this.btnHome.IdleIconRightImage = null;
            this.btnHome.IndicateFocus = true;
            this.btnHome.Location = new System.Drawing.Point(55, 160);
            this.btnHome.Name = "btnHome";
            this.btnHome.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnHome.OnDisabledState.BorderRadius = 35;
            this.btnHome.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnHome.OnDisabledState.BorderThickness = 1;
            this.btnHome.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnHome.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnHome.OnDisabledState.IconLeftImage = null;
            this.btnHome.OnDisabledState.IconRightImage = null;
            this.btnHome.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(42)))), ((int)(((byte)(133)))));
            this.btnHome.onHoverState.BorderRadius = 35;
            this.btnHome.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnHome.onHoverState.BorderThickness = 1;
            this.btnHome.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(42)))), ((int)(((byte)(133)))));
            this.btnHome.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnHome.onHoverState.IconLeftImage = null;
            this.btnHome.onHoverState.IconRightImage = null;
            this.btnHome.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(252)))), ((int)(((byte)(175)))), ((int)(((byte)(23)))));
            this.btnHome.OnIdleState.BorderRadius = 35;
            this.btnHome.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnHome.OnIdleState.BorderThickness = 1;
            this.btnHome.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(252)))), ((int)(((byte)(175)))), ((int)(((byte)(23)))));
            this.btnHome.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnHome.OnIdleState.IconLeftImage = null;
            this.btnHome.OnIdleState.IconRightImage = null;
            this.btnHome.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(42)))), ((int)(((byte)(133)))));
            this.btnHome.OnPressedState.BorderRadius = 35;
            this.btnHome.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnHome.OnPressedState.BorderThickness = 1;
            this.btnHome.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnHome.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnHome.OnPressedState.IconLeftImage = null;
            this.btnHome.OnPressedState.IconRightImage = null;
            this.btnHome.Size = new System.Drawing.Size(173, 41);
            this.btnHome.TabIndex = 2;
            this.btnHome.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnHome.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnHome.TextMarginLeft = 0;
            this.btnHome.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnHome.UseDefaultRadiusAndThickness = true;
            this.btnHome.Click += new System.EventHandler(this.btnHome_Click);
            // 
            // btnCustomer
            // 
            this.btnCustomer.AllowAnimations = true;
            this.btnCustomer.AllowMouseEffects = true;
            this.btnCustomer.AllowToggling = true;
            this.btnCustomer.AnimationSpeed = 200;
            this.btnCustomer.AutoGenerateColors = false;
            this.btnCustomer.AutoRoundBorders = false;
            this.btnCustomer.AutoSizeLeftIcon = true;
            this.btnCustomer.AutoSizeRightIcon = true;
            this.btnCustomer.BackColor = System.Drawing.Color.Transparent;
            this.btnCustomer.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(252)))), ((int)(((byte)(175)))), ((int)(((byte)(23)))));
            this.btnCustomer.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnCustomer.BackgroundImage")));
            this.btnCustomer.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCustomer.ButtonText = "Customer";
            this.btnCustomer.ButtonTextMarginLeft = 0;
            this.btnCustomer.ColorContrastOnClick = 45;
            this.btnCustomer.ColorContrastOnHover = 45;
            this.btnCustomer.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges7.BottomLeft = true;
            borderEdges7.BottomRight = true;
            borderEdges7.TopLeft = true;
            borderEdges7.TopRight = true;
            this.btnCustomer.CustomizableEdges = borderEdges7;
            this.btnCustomer.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnCustomer.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnCustomer.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnCustomer.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnCustomer.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnCustomer.Font = new System.Drawing.Font("Segoe UI Semibold", 11F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnCustomer.ForeColor = System.Drawing.Color.White;
            this.btnCustomer.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnCustomer.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btnCustomer.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnCustomer.IconMarginLeft = 11;
            this.btnCustomer.IconPadding = 10;
            this.btnCustomer.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnCustomer.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btnCustomer.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnCustomer.IconSize = 25;
            this.btnCustomer.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(252)))), ((int)(((byte)(175)))), ((int)(((byte)(23)))));
            this.btnCustomer.IdleBorderRadius = 35;
            this.btnCustomer.IdleBorderThickness = 1;
            this.btnCustomer.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(252)))), ((int)(((byte)(175)))), ((int)(((byte)(23)))));
            this.btnCustomer.IdleIconLeftImage = null;
            this.btnCustomer.IdleIconRightImage = null;
            this.btnCustomer.IndicateFocus = true;
            this.btnCustomer.Location = new System.Drawing.Point(55, 385);
            this.btnCustomer.Name = "btnCustomer";
            this.btnCustomer.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnCustomer.OnDisabledState.BorderRadius = 35;
            this.btnCustomer.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCustomer.OnDisabledState.BorderThickness = 1;
            this.btnCustomer.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnCustomer.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnCustomer.OnDisabledState.IconLeftImage = null;
            this.btnCustomer.OnDisabledState.IconRightImage = null;
            this.btnCustomer.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(42)))), ((int)(((byte)(133)))));
            this.btnCustomer.onHoverState.BorderRadius = 35;
            this.btnCustomer.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCustomer.onHoverState.BorderThickness = 1;
            this.btnCustomer.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(42)))), ((int)(((byte)(133)))));
            this.btnCustomer.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnCustomer.onHoverState.IconLeftImage = null;
            this.btnCustomer.onHoverState.IconRightImage = null;
            this.btnCustomer.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(252)))), ((int)(((byte)(175)))), ((int)(((byte)(23)))));
            this.btnCustomer.OnIdleState.BorderRadius = 35;
            this.btnCustomer.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCustomer.OnIdleState.BorderThickness = 1;
            this.btnCustomer.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(252)))), ((int)(((byte)(175)))), ((int)(((byte)(23)))));
            this.btnCustomer.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnCustomer.OnIdleState.IconLeftImage = null;
            this.btnCustomer.OnIdleState.IconRightImage = null;
            this.btnCustomer.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(42)))), ((int)(((byte)(133)))));
            this.btnCustomer.OnPressedState.BorderRadius = 35;
            this.btnCustomer.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCustomer.OnPressedState.BorderThickness = 1;
            this.btnCustomer.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnCustomer.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnCustomer.OnPressedState.IconLeftImage = null;
            this.btnCustomer.OnPressedState.IconRightImage = null;
            this.btnCustomer.Size = new System.Drawing.Size(173, 41);
            this.btnCustomer.TabIndex = 6;
            this.btnCustomer.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnCustomer.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnCustomer.TextMarginLeft = 0;
            this.btnCustomer.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnCustomer.UseDefaultRadiusAndThickness = true;
            this.btnCustomer.Click += new System.EventHandler(this.btnCustomer_Click);
            // 
            // btnCategory
            // 
            this.btnCategory.AllowAnimations = true;
            this.btnCategory.AllowMouseEffects = true;
            this.btnCategory.AllowToggling = true;
            this.btnCategory.AnimationSpeed = 200;
            this.btnCategory.AutoGenerateColors = false;
            this.btnCategory.AutoRoundBorders = false;
            this.btnCategory.AutoSizeLeftIcon = true;
            this.btnCategory.AutoSizeRightIcon = true;
            this.btnCategory.BackColor = System.Drawing.Color.Transparent;
            this.btnCategory.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(252)))), ((int)(((byte)(175)))), ((int)(((byte)(23)))));
            this.btnCategory.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnCategory.BackgroundImage")));
            this.btnCategory.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCategory.ButtonText = "Category";
            this.btnCategory.ButtonTextMarginLeft = 0;
            this.btnCategory.ColorContrastOnClick = 45;
            this.btnCategory.ColorContrastOnHover = 45;
            this.btnCategory.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges8.BottomLeft = true;
            borderEdges8.BottomRight = true;
            borderEdges8.TopLeft = true;
            borderEdges8.TopRight = true;
            this.btnCategory.CustomizableEdges = borderEdges8;
            this.btnCategory.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnCategory.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnCategory.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnCategory.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnCategory.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnCategory.Font = new System.Drawing.Font("Segoe UI Semibold", 11F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnCategory.ForeColor = System.Drawing.Color.White;
            this.btnCategory.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnCategory.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btnCategory.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnCategory.IconMarginLeft = 11;
            this.btnCategory.IconPadding = 10;
            this.btnCategory.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnCategory.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btnCategory.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnCategory.IconSize = 25;
            this.btnCategory.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(252)))), ((int)(((byte)(175)))), ((int)(((byte)(23)))));
            this.btnCategory.IdleBorderRadius = 35;
            this.btnCategory.IdleBorderThickness = 1;
            this.btnCategory.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(252)))), ((int)(((byte)(175)))), ((int)(((byte)(23)))));
            this.btnCategory.IdleIconLeftImage = null;
            this.btnCategory.IdleIconRightImage = null;
            this.btnCategory.IndicateFocus = true;
            this.btnCategory.Location = new System.Drawing.Point(55, 235);
            this.btnCategory.Name = "btnCategory";
            this.btnCategory.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnCategory.OnDisabledState.BorderRadius = 35;
            this.btnCategory.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCategory.OnDisabledState.BorderThickness = 1;
            this.btnCategory.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnCategory.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnCategory.OnDisabledState.IconLeftImage = null;
            this.btnCategory.OnDisabledState.IconRightImage = null;
            this.btnCategory.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(42)))), ((int)(((byte)(133)))));
            this.btnCategory.onHoverState.BorderRadius = 35;
            this.btnCategory.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCategory.onHoverState.BorderThickness = 1;
            this.btnCategory.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(42)))), ((int)(((byte)(133)))));
            this.btnCategory.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnCategory.onHoverState.IconLeftImage = null;
            this.btnCategory.onHoverState.IconRightImage = null;
            this.btnCategory.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(252)))), ((int)(((byte)(175)))), ((int)(((byte)(23)))));
            this.btnCategory.OnIdleState.BorderRadius = 35;
            this.btnCategory.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCategory.OnIdleState.BorderThickness = 1;
            this.btnCategory.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(252)))), ((int)(((byte)(175)))), ((int)(((byte)(23)))));
            this.btnCategory.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnCategory.OnIdleState.IconLeftImage = null;
            this.btnCategory.OnIdleState.IconRightImage = null;
            this.btnCategory.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(42)))), ((int)(((byte)(133)))));
            this.btnCategory.OnPressedState.BorderRadius = 35;
            this.btnCategory.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCategory.OnPressedState.BorderThickness = 1;
            this.btnCategory.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnCategory.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnCategory.OnPressedState.IconLeftImage = null;
            this.btnCategory.OnPressedState.IconRightImage = null;
            this.btnCategory.Size = new System.Drawing.Size(173, 41);
            this.btnCategory.TabIndex = 3;
            this.btnCategory.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnCategory.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnCategory.TextMarginLeft = 0;
            this.btnCategory.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnCategory.UseDefaultRadiusAndThickness = true;
            this.btnCategory.Click += new System.EventHandler(this.btnCategory_Click);
            // 
            // btnProduct
            // 
            this.btnProduct.AllowAnimations = true;
            this.btnProduct.AllowMouseEffects = true;
            this.btnProduct.AllowToggling = true;
            this.btnProduct.AnimationSpeed = 200;
            this.btnProduct.AutoGenerateColors = false;
            this.btnProduct.AutoRoundBorders = false;
            this.btnProduct.AutoSizeLeftIcon = true;
            this.btnProduct.AutoSizeRightIcon = true;
            this.btnProduct.BackColor = System.Drawing.Color.Transparent;
            this.btnProduct.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(252)))), ((int)(((byte)(175)))), ((int)(((byte)(23)))));
            this.btnProduct.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnProduct.BackgroundImage")));
            this.btnProduct.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnProduct.ButtonText = "Product";
            this.btnProduct.ButtonTextMarginLeft = 0;
            this.btnProduct.ColorContrastOnClick = 45;
            this.btnProduct.ColorContrastOnHover = 45;
            this.btnProduct.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges9.BottomLeft = true;
            borderEdges9.BottomRight = true;
            borderEdges9.TopLeft = true;
            borderEdges9.TopRight = true;
            this.btnProduct.CustomizableEdges = borderEdges9;
            this.btnProduct.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnProduct.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnProduct.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnProduct.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnProduct.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnProduct.Font = new System.Drawing.Font("Segoe UI Semibold", 11F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnProduct.ForeColor = System.Drawing.Color.White;
            this.btnProduct.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnProduct.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btnProduct.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnProduct.IconMarginLeft = 11;
            this.btnProduct.IconPadding = 10;
            this.btnProduct.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnProduct.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btnProduct.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnProduct.IconSize = 25;
            this.btnProduct.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(252)))), ((int)(((byte)(175)))), ((int)(((byte)(23)))));
            this.btnProduct.IdleBorderRadius = 35;
            this.btnProduct.IdleBorderThickness = 1;
            this.btnProduct.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(252)))), ((int)(((byte)(175)))), ((int)(((byte)(23)))));
            this.btnProduct.IdleIconLeftImage = null;
            this.btnProduct.IdleIconRightImage = null;
            this.btnProduct.IndicateFocus = true;
            this.btnProduct.Location = new System.Drawing.Point(55, 310);
            this.btnProduct.Name = "btnProduct";
            this.btnProduct.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnProduct.OnDisabledState.BorderRadius = 35;
            this.btnProduct.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnProduct.OnDisabledState.BorderThickness = 1;
            this.btnProduct.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnProduct.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnProduct.OnDisabledState.IconLeftImage = null;
            this.btnProduct.OnDisabledState.IconRightImage = null;
            this.btnProduct.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(42)))), ((int)(((byte)(133)))));
            this.btnProduct.onHoverState.BorderRadius = 35;
            this.btnProduct.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnProduct.onHoverState.BorderThickness = 1;
            this.btnProduct.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(42)))), ((int)(((byte)(133)))));
            this.btnProduct.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnProduct.onHoverState.IconLeftImage = null;
            this.btnProduct.onHoverState.IconRightImage = null;
            this.btnProduct.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(252)))), ((int)(((byte)(175)))), ((int)(((byte)(23)))));
            this.btnProduct.OnIdleState.BorderRadius = 35;
            this.btnProduct.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnProduct.OnIdleState.BorderThickness = 1;
            this.btnProduct.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(252)))), ((int)(((byte)(175)))), ((int)(((byte)(23)))));
            this.btnProduct.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnProduct.OnIdleState.IconLeftImage = null;
            this.btnProduct.OnIdleState.IconRightImage = null;
            this.btnProduct.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(42)))), ((int)(((byte)(133)))));
            this.btnProduct.OnPressedState.BorderRadius = 35;
            this.btnProduct.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnProduct.OnPressedState.BorderThickness = 1;
            this.btnProduct.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnProduct.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnProduct.OnPressedState.IconLeftImage = null;
            this.btnProduct.OnPressedState.IconRightImage = null;
            this.btnProduct.Size = new System.Drawing.Size(173, 41);
            this.btnProduct.TabIndex = 5;
            this.btnProduct.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnProduct.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnProduct.TextMarginLeft = 0;
            this.btnProduct.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnProduct.UseDefaultRadiusAndThickness = true;
            this.btnProduct.Click += new System.EventHandler(this.btnProduct_Click);
            // 
            // flowLayoutPanel
            // 
            this.flowLayoutPanel.BackColor = System.Drawing.Color.WhiteSmoke;
            this.flowLayoutPanel.Location = new System.Drawing.Point(260, 3);
            this.flowLayoutPanel.Name = "flowLayoutPanel";
            this.flowLayoutPanel.Size = new System.Drawing.Size(1095, 951);
            this.flowLayoutPanel.TabIndex = 14;
            // 
            // AdminMainPage
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.WhiteSmoke;
            this.ClientSize = new System.Drawing.Size(1432, 930);
            this.Controls.Add(this.flowLayoutPanel);
            this.Controls.Add(this.guna2Panel1);
            this.Controls.Add(this.controlboxTurnOff);
            this.Controls.Add(this.controlboxMinimize);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "AdminMainPage";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "AdminMainPage";
            this.Load += new System.EventHandler(this.AdminMainPage_Load);
            this.guna2Panel1.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.bunifuPictureBox1)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private Guna.UI2.WinForms.Guna2ControlBox controlboxTurnOff;
        private Guna.UI2.WinForms.Guna2ControlBox controlboxMinimize;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnOrder;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnCustomer;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnProduct;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnCategory;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnHome;
        private Guna.UI2.WinForms.Guna2Panel guna2Panel1;
        private System.Windows.Forms.FlowLayoutPanel flowLayoutPanel;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnColor;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnSize;
        private Bunifu.UI.WinForms.BunifuPictureBox bunifuPictureBox1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnProvider;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnSubcategory;
    }
}